import {
  Alert,
  Dialog,
  Grid,
  Slide,
  Snackbar,
  TextField,
  Typography,
} from "@mui/material";
import React, { useEffect, useState } from "react";
import { useTheme } from "@mui/material/styles";
import useMediaQuery from "@mui/material/useMediaQuery";
import styles from "../../styles/Contact.module.css";
import { useRef } from "react";
import LocalPhoneOutlinedIcon from "@mui/icons-material/LocalPhoneOutlined";
import WhatsAppIcon from "@mui/icons-material/WhatsApp";
import NearMeOutlinedIcon from "@mui/icons-material/NearMeOutlined";
import EmailOutlinedIcon from "@mui/icons-material/EmailOutlined";
import { useRouter } from "next/router";
import Image from "next/image";

const CancellationsPolicy = ({ detailsData, contactData }) => {
  const theme = useTheme();
  const [open, setopen] = useState(false);
  const bkcolor = "white";
  const [ischecked, setisChecked] = useState(true);
  const router = useRouter();
  const packageName = router.query.packageName;
  const Transition = React.forwardRef(function Transition(props, ref) {
    return <Slide direction="up" ref={ref} {...props} />;
  });

  const handleOpen = () => {
    setopen(true);
  };

  const handleClose = () => {
    setopen(false);
  };

  const sendEmail = (e) => {
    e.preventDefault();

    sendForm(
      "service_h37zmnt",
      "template_jpglnfc",
      form.current,
      "uxUACuGSvix8kkLqR"
    )
      .then(
        (result) => {
          handleOpen();
          console.log(result.text);
        },
        (error) => {
          console.log(error.text);
        }
      )
      .finally(() => {
        document.getElementById("myForm").reset();
      });
  };

  const styleTypo = {
    fontFamily: "Roboto, 'cursive'",
    fontSize: { xs: "12px", md: "1.2vw" },
    fontWeight: "500",
    flexWrap: "wrap",
  };
  const form = useRef();
  const isMobile = useMediaQuery(theme.breakpoints.down("md"), {
    defaultMatches: true,
  });

  return (
    <div>
      <Head>
        <title>Cancellations Policy - Discover Kashmir</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />{" "}
      </Head>
      <Grid container>
        <HeroSection
          usedIn="Contact"
          bgImage="background.jpg"
          Name={"Cancellations Policy"}
        />
        <Grid
          container
          sx={{
            display: "flex",
            flexDirection: { xs: "column", md: "row" },
            width: "100vw",
          }}
        >
          <Grid
            item
            className={styles.cnInnerContainerRight}
            sx={{ width: { xs: "100vw", md: "100vw" } }}
          >
            <Grid container className={styles.cnRightContainer}>
              <Grid item>
                <Typography
                  sx={{
                    fontSize: { xs: "17px", md: "30px" },
                    fontWeight: "700",
                    pb: "10px",
                  }}
                >
                  NO REFUND SHALL BE MADE WITH RESPECT TO THE INITIAL BOOKING
                  AMOUNT FOR ANY CANCELLATIONS. HOWEVER,
                </Typography>
                <Typography
                  sx={{ fontSize: { xs: "9px", md: "16px" }, color: "gray" }}
                >
                  <ul>
                    <li style={{ padding: "12px", fontFamily: "monospace" }}>
                      {" "}
                      If Cancellations Are Made 30 Days Before The Start Date Of
                      The Trip, 50% Of The Trip Cost Will Be Charged As
                      Cancellation Fees.
                    </li>
                    <li style={{ padding: "12px", fontFamily: "monospace" }}>
                      If Cancellations Are Made 15-30 Days Before The Start Date
                      Of The Trip, 75% Of The Trip Cost Will Be Charged As
                      Cancellation Fees.
                    </li>
                    <li style={{ padding: "12px", fontFamily: "monospace" }}>
                      If Cancellations Are Made Within 0-15 Days Before The
                      Start Date Of The Trip, 100% Of The Trip Cost Will Be
                      Charged As Cancellation Fees.
                    </li>
                    <li style={{ padding: "12px", fontFamily: "monospace" }}>
                      In The Case Of Unforeseen Weather Conditions Or Government
                      Restrictions, Certain Activities May Be Canceled And In
                      Such Cases, The Operator Will Try His Best To Provide An
                      Alternate Feasible Activity.However, No Refund Will Be
                      Provided For The Same.
                    </li>
                  </ul>
                </Typography>
                <Typography
                  sx={{
                    fontSize: { xs: "15px", md: "18px" },
                    fontWeight: "700",
                    p: "10px",
                  }}
                >
                  Cancellations Policy Will Differ During The Peak Season And In
                  Popular Places.
                </Typography>
              </Grid>
            </Grid>
          </Grid>
        </Grid>
      </Grid>
    </div>
  );
};

export default CancellationsPolicy;

import path from "path";
import fsPromises from "fs/promises";
import Head from "next/head";
import { sendForm } from "@emailjs/browser";
import dynamic from "next/dynamic";
import HeroSection from "../../Components/HeroSection";
export async function getStaticProps() {
  const jsonDirectory = path.join(process.cwd(), "Data");
  //Read the json data file data.json
  const detailsData = await fsPromises.readFile(
    jsonDirectory + "/Details.json",
    "utf8"
  );
  const contactData = await fsPromises.readFile(
    jsonDirectory + "/Contact.json",
    "utf8"
  );
  return {
    props: {
      detailsData: JSON.parse(detailsData),
      contactData: JSON.parse(contactData),
    },
  };
}
